### ISSUE TITLE
Using Angular filters

### ISSUE THREAD

**Issue by BigPoppaG** [morgan-del/flask-triangle#26]
Hi there. Can you still use angularjs built-in filters with flask-triangle?
eg. <div>{{product.price | angular | currency}}</div>
This errors with "currency filter not found" type error.
Many thanks.

**Comment by DjingoDjango** [comment]
bump

**Comment by morgan-del** [comment]
If you write ``{{product.price | angular | currency}}``, ``currency`` is considered as another Jinja filter, this is why you end up with an error. I don't see any self explanatory solution to tell such filter must be processed by such template engine but as a workaround you can do ``{{"product.price|currency" | angular }}``.

If you have any suggestion to handle this, I will re-open this issue.
